---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.16.2
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
---

<!-- #region editable=true slideshow={"slide_type": ""} -->
# Counterfeit detection
<!-- #endregion -->

The task in this assignment is to detect the  counterfeit banknotes. The data set is based on [banknote authentication Data Set ](https://archive.ics.uci.edu/ml/datasets/banknote+authentication#) from UCI Machine Learning repository. The first three columns denote different parameters obtained from the photographs of the banknotes and last colum provides the label. Frankly as the dataset does not have any description I don't know  which labels corresponds to real and which to counterfeited banknotes. let's assume that label one (positive) denotes the clounterfeits. The set  [banknote_authentication.csv](./data/banknote_authentication.csv) can be found in the `data`  directory.

```{python}
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as st
```

```{python}
from sklearn.metrics import classification_report, ConfusionMatrixDisplay
```

```{python}
import  matplotlib.pyplot as plt
plt.rcParams['figure.figsize']=(8,8)
```

Please insert you  firstname  and name below

```{python}
from  sklearn.model_selection import train_test_split
seed = 31287
```

```{python}
data = pd.read_csv('data/banknotes_data.csv')
```

```{python}
data.head()
```

```{python tags=c("skip")}
data.describe()
```

```{python tags=c("skip")}
data.info()
```

```{python}
data_train, data_test = train_test_split(data, test_size=0.2, shuffle=True, stratify=data.loc[:,'counterfeit'], random_state=seed)
```

```{python}
data_train
```

```{python}
lbls_train = data_train['counterfeit']
lbls_test = data_test['counterfeit']
```

```{python}
fig, ax = plt.subplots(1,4, figsize=(22,5))
for i in range(4):
    ax[i].hist(data_train[lbls_train==0].iloc[:,i], bins=32, histtype='step', color='blue')
    ax[i].hist(data_train[lbls_train==1].iloc[:,i], bins=32, histtype='step', color='red')
    ax[i].hist(data_train[lbls_train==0].iloc[:,i], bins=32, histtype='bar', color='lightblue', alpha=0.25)
    ax[i].hist(data_train[lbls_train==1].iloc[:,i], bins=32, histtype='bar', color='orange', alpha =0.25)
```

<!-- #region editable=true slideshow={"slide_type": ""} -->
# Problem 1
<!-- #endregion -->

<!-- #region editable=true slideshow={"slide_type": ""} -->
Train a neural network classifier to predict counterfeit banknotes. Use the features `a0` and `a3`. Calculate the confussion matrix  and AUC score. 
<!-- #endregion -->

```{python editable=TRUE, slideshow={'slide_type': ''}}
import torch
import torch.nn as tnn
import torch.optim as optim
from sklearn.metrics import roc_auc_score, confusion_matrix, ConfusionMatrixDisplay
```

```{python editable=TRUE, slideshow={'slide_type': ''}}
features= [0, 3]
nf=len(features)
```

```{python editable=TRUE, slideshow={'slide_type': ''}}
features_train = torch.from_numpy(data_train.values[:,features]).to(dtype=torch.float32)
labels_train = torch.from_numpy(data_train.values[:,4:5]).to(dtype=torch.float32)
```

```{python editable=TRUE, slideshow={'slide_type': ''}}
features_test = torch.from_numpy(data_test.values[:,features]).to(dtype=torch.float32)
labels_test = torch.from_numpy(data_test.values[:,4:5]).to(dtype=torch.float32)
```

```{python editable=TRUE, slideshow={'slide_type': ''}}
model = tnn.Sequential(tnn.Linear(in_features=nf, out_features=1), tnn.Sigmoid())
```

```{python editable=TRUE, slideshow={'slide_type': ''}}
from sklearn.metrics import roc_curve, confusion_matrix, accuracy_score
```

```{python editable=TRUE, slideshow={'slide_type': ''}}
y_true = labels_test.numpy()
with torch.no_grad():
  y_proba = model(features_test);
  y_predicted = 1*(y_proba>0.5)
```

```{python}
model = tnn.Sequential(
    tnn.Linear(in_features=nf, out_features=256),
    tnn.ReLU(),
    tnn.Dropout(0.5),
    tnn.Linear(in_features=256, out_features=128),
    tnn.ReLU(),
    tnn.Dropout(0.3),
    tnn.Linear(in_features=128, out_features=64),
    tnn.ReLU(),
    tnn.Linear(in_features=64, out_features=1),
    tnn.Sigmoid()
)

optimizer = optim.Adam(model.parameters(), lr=0.0005) 
criterion = tnn.BCELoss()
num_epochs = 2500
best_loss_valid = float('inf')
patience = 100
current_patience = 0

for epoch in range(num_epochs):
    model.train()
    optimizer.zero_grad()
    outputs = model(features_train)
    loss = criterion(outputs, labels_train)
    loss.backward()
    optimizer.step()
    
    if (epoch + 1) % 100 == 0:
        model.eval()
        with torch.no_grad():
            outputs_valid = model(features_test)
            loss_valid = criterion(outputs_valid, labels_test)
        
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}, Validation Loss: {loss_valid.item():.4f}')
        
        if loss_valid < best_loss_valid:
            best_loss_valid = loss_valid
            current_patience = 0
        else:
            current_patience += 1
            if current_patience > patience:
                print(f'Validation loss did not improve, stopping.')
                break
model.eval()
with torch.no_grad():
    y_proba = model(features_test)
    y_predicted = (y_proba > 0.5).float()
    y_true = labels_test
    conf_matrix = confusion_matrix(y_true, y_predicted.numpy())
    auc_score = roc_auc_score(y_true, y_proba.numpy())

print('Confusion Matrix is:\n', conf_matrix)
print(f'AUC Score is: {auc_score:.4f}')
```

```{python editable=TRUE, slideshow={'slide_type': ''}}
accuracy_score(y_true, y_pred=y_predicted)
```
